Check iria
GroupLe/missing-mangas pull request #5
Opened 2021-07-17 15:33 UTC by vaskers5

2021-07-17 16:14 UTC, ARQtty requested changes

2021-07-17 16:14 UTC, ARQtty commented on entities/validation.py
> +    def __init__(self, test: pd.DataFrame, predict: pd.DataFrame):
это не датафреймы, а серии

2021-07-17 16:14 UTC, ARQtty commented on entities/validation.py
> +    def __init__(self, test: pd.DataFrame, predict: pd.DataFrame):
Поле класса создано, но нигде не использовано 
Зачем?

2021-07-17 16:14 UTC, ARQtty commented on entities/validation.py
> +        df = pd.DataFrame(metrics, index=[0])
Запись/чтение с диска - это очень долгая операция. Почему нельзя передать по ссылке?

2021-07-17 16:14 UTC, ARQtty commented on entities/validation.py
> +            result_df.to_csv(path_to_csv, index=False)
непонятно что за датафрейм вообще читается

2021-07-17 16:14 UTC, ARQtty commented on entities/validation.py
> +        try:
try-except'ы выглядят костыльно. Не понял, в чём цель ветвления, но можно сделать без создания и обработки ошибки

2021-07-17 16:30 UTC, vaskers5 commented on entities/validation.py
> +    def __init__(self, test: pd.DataFrame, predict: pd.DataFrame):
Поле класса? Ты имеешь в виду что я храню test, predict как поля класса?

2021-07-17 16:36 UTC, vaskers5 commented on entities/validation.py
> +            result_df.to_csv(path_to_csv, index=False)
Предполагается, что уже был создан csv  с таблицей результатов определенной модели, путь к которому передается и после туда записываются новые результаты

2021-07-17 16:37 UTC, vaskers5 commented on entities/validation.py
> +        try:
try-except здесь заюзан как раз таки для того случая, если вдруг пользователь  не создал файл с прыдущими данными, а лишь вносит свои первые измерения

2021-07-17 16:38 UTC, vaskers5 commented on entities/validation.py
> +        df = pd.DataFrame(metrics, index=[0])
О какой скорости вообще идет речь, когда мы вычисляем 4 метрики, думаю считывание даже 100 строк предыдущих измерений никак не повлияет на нашу скорость

2021-07-17 16:39 UTC, vaskers5 commented on entities/validation.py
> +        df = pd.DataFrame(metrics, index=[0])
по ссылке нельзя передать, что в таком случае это рушит всю логику написанного класса, который сохраняет данные вот в таком виде
![image](https://user-images.githubusercontent.com/48238046/126043814-c963c054-6ad6-4a7a-92d1-1cb9e65f9eaf.png)

2021-07-17 17:04 UTC, ARQtty commented on entities/validation.py
> +    def __init__(self, test: pd.DataFrame, predict: pd.DataFrame):
yes

2021-07-17 17:05 UTC, ARQtty commented on entities/validation.py
> +        df = pd.DataFrame(metrics, index=[0])
всё ещё не понял, почему нельзя передать по ссылке датафрейм, который читается с диска

2021-07-17 17:05 UTC, ARQtty commented on entities/validation.py
> +            result_df.to_csv(path_to_csv, index=False)
Неуверенное предположение. Лучше не строить никаких предположений, а передавать объект по ссылке

2021-07-17 17:06 UTC, ARQtty commented on entities/validation.py
> +        try:
Так это же логика не валидадтора, а какого-нибудь сохраняющего модуля. Дело валидатора - считать метрики и отдавать результат. Отдавать. Return.

2021-07-17 17:58 UTC, vaskers5 commented on entities/validation.py
> +        df = pd.DataFrame(metrics, index=[0])
Исправил, проверяй

2021-07-17 18:01 UTC, ARQtty commented
Вообще если очень хочется что-то дописать в файл, который может быть ещё не создан, присмотрись к режиму открытия файлов "a". Это аргумент функции open()

2021-07-17 18:17 UTC, vaskers5 commented
> Вообще если очень хочется что-то дописать в файл, который может быть ещё не создан, присмотрись к режиму открытия файлов "a". Это аргумент функции open()

Усек, что насчет последней версии валидатора

2021-07-17 22:23 UTC, ARQtty requested changes

2021-07-17 22:23 UTC, ARQtty commented on entities/validation.py
> +        df = pd.DataFrame(metrics, index=[0])
Хорошо, что передаётся по ссылке. Теперь код быстрый. Но класс работает вне зоны своей ответственности. Просто верни уже метрики из метода, потом решишь что с ними делать

2021-07-18 08:16 UTC, ARQtty requested changes

2021-07-18 08:16 UTC, ARQtty commented on entities/validation.py
> +    def validate(test: pd.Series, pred: pd.Series) -> defaultdict:
зачем возвращать не обычный словарь? Если есть выбор, стоит оставлять обычные типы

2021-07-18 08:16 UTC, ARQtty commented on entities/validation.py
> +    def validate(test: pd.Series, pred: pd.Series) -> defaultdict:
при том, что ты вообще не пользуешься здесь отличием defaultdict от обычного словаря

2021-07-18 10:06 UTC, vaskers5 commented on entities/validation.py
> +    def validate(test: pd.Series, pred: pd.Series) -> defaultdict:
почему - использу при заполнении самого словаря, исправлю на дефолтный

2021-07-18 10:17 UTC, merged