add class for data reprezentation
GroupLe/missing-mangas pull request #6
Opened 2021-07-18 12:17 UTC by vaskers5

2021-07-20 14:57 UTC, ARQtty requested changes

2021-07-20 14:57 UTC, ARQtty commented on configs/config_validate.yaml
> +  path: './data/raw/validate/first_test_set.csv'
first и second? 
нейминг говно

2021-07-20 14:57 UTC, ARQtty commented on configs/config_validate.yaml
> +  name_cols: ['g_name', 'g_eng_name']
я знаю, что за g_ и r_, а другие разработчики?

2021-07-20 14:57 UTC, ARQtty commented on configs/config_validate.yaml
> +validate_df:
А вот этого кажется в других конфигах не было. Если ты кладешь конфиг в папку с другими конфигами, даешь ему такое же имя и явно следуешь формату существующих конфигов, то нужно следовать ему полностью.

2021-07-20 14:57 UTC, ARQtty commented on entities/matchers.py
> +        for j, mtitle in enumerate(self.titles):
То есть единственного отображающего длительный процесс прогрессбара в коде больше нет?

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +    def check_names(Title_first, other):
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +        for Title_second in other:
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +            if pd.isna(Title_second):
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +            for name in Title_second.names:
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +                if name not in Title_first.names:
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +    def check_names(Title_first, other):
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +        for Title_second in other:
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +            if pd.isna(Title_second):
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +            for lang in Title_first.names:
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +                for name in Title_second.names[lang]:
pep8

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +                    if name not in Title_first.names[lang]:
pep8

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +    gtitles = [TitleEntity(list(source_manga_names[i]),
не можешь писать достаточно кратко для list comprehension в одну строку - не пользуйся list comprehension

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +    target_manga_names = list(
зачем этот каст

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +    k = -1
я знаю зачем k, а ты? И зачем оно здесь?

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +        match_res = list(map(TitleEntity.check_names, gtitles,list(pool.imap(matcher.find_matches,
Нейминг говно

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +        match_res = list(map(TitleEntity.check_names, gtitles,list(pool.imap(matcher.find_matches,
зачем два map'а я так и не понял. Выглядит слишком нагруженно

2021-07-20 14:57 UTC, ARQtty commented on entities/titles.py
> +    def check_names(Title_first, other):
нейминг говно бтв

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +                                            target_df,
включи линтер и не выключай

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +                                            labels, TitleEntitys[name_title],
pep8

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +            ReprezentData.create_csv(metrics,
typo

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +            if name_title == "CompareByLanguageCatBoostTitle":
имя заголовок? Кто-то так говорит на английском?

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +                MatcherEntitys.pop("CatboostFullMatcher")
typo

2021-07-20 14:57 UTC, ARQtty commented on validation.py
> +                MatcherEntitys.pop("CatboostFullMatcher")
это статик метод, который дропает что-то из переданной строки? Или что? Ничего не понятно, если не открыть определение

2021-07-20 17:52 UTC, vaskers5 commented on entities/matchers.py
> +        for j, mtitle in enumerate(self.titles):
это тот прогресс бар из-за которого вылезали те it, которые я тебе вчера скидывал. Прогресс бар который отображает сам процесс остался.

2021-07-20 18:10 UTC, vaskers5 commented on configs/config_validate.yaml
> +  path: './data/raw/validate/first_test_set.csv'
fixed

2021-07-20 18:10 UTC, vaskers5 commented on configs/config_validate.yaml
> +  name_cols: ['g_name', 'g_eng_name']
fixed

2021-07-20 18:10 UTC, vaskers5 commented on configs/config_validate.yaml
> +validate_df:
fixed

2021-07-20 20:31 UTC, vaskers5 commented on validation.py
> +    k = -1
это твое k)

2021-07-20 20:31 UTC, vaskers5 commented on validation.py
> +    k = -1
чекни код своего матчера

2021-07-20 20:33 UTC, vaskers5 commented on validation.py
> +    target_manga_names = list(
опять же, твой код)

2021-07-20 20:33 UTC, vaskers5 commented on validation.py
> +    gtitles = [TitleEntity(list(source_manga_names[i]),
ДА ЭТО ТОЖЕ ТВОЙ КОД

2021-07-20 20:33 UTC, ARQtty commented on validation.py
> +    k = -1
Да я знаю, что это моё. Но я этим пользовался в продуктовом матчере. А ты скопировал, не посмотрев на то, нужно оно тут или нет

2021-07-21 16:35 UTC, ARQtty requested changes

2021-07-21 16:35 UTC, ARQtty commented on entities/titles.py
> +    def validate_titles(validation_title, matched_titles):
типы

2021-07-21 16:35 UTC, ARQtty commented on entities/titles.py
> +    def validate_titles(validation_title, matched_titles):
типы

2021-07-22 20:24 UTC, ARQtty commented on entities/titles.py
> +    @staticmethod
В результате исследования стаковервлоу: лучше вариант - писать аннотации в docstring

2021-07-22 20:25 UTC, ARQtty reviewed
Всё ок, добавь шаг пайплайна со сбором результатов в одну таблицу

2021-07-25 22:29 UTC, ARQtty approved these changes

2021-07-25 22:29 UTC, merged